"""second

Revision ID: 3d38d924adbc
Revises: bb179f04e2d2
Create Date: 2025-03-11 19:09:45.414805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d38d924adbc'
down_revision: Union[str, None] = 'bb179f04e2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_stock_id', table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code_act', sa.VARCHAR(length=50), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ltp', sa.FLOAT(), nullable=False),
    sa.Column('price_open', sa.FLOAT(), nullable=False),
    sa.Column('high', sa.FLOAT(), nullable=False),
    sa.Column('low', sa.FLOAT(), nullable=False),
    sa.Column('closeyest', sa.FLOAT(), nullable=False),
    sa.Column('change', sa.FLOAT(), nullable=False),
    sa.Column('change_percent', sa.FLOAT(), nullable=False),
    sa.Column('volume', sa.BIGINT(), nullable=False),
    sa.Column('volume_avg', sa.BIGINT(), nullable=False),
    sa.Column('marketcap', sa.BIGINT(), nullable=False),
    sa.Column('pe_ratio', sa.FLOAT(), nullable=False),
    sa.Column('eps', sa.FLOAT(), nullable=False),
    sa.Column('outstanding_shares', sa.BIGINT(), nullable=False),
    sa.Column('week_52_high', sa.FLOAT(), nullable=False),
    sa.Column('week_52_low', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('traded_time', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code_act'),
    sa.UniqueConstraint('company_name')
    )
    op.create_index('ix_stock_id', 'stock', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    # ### end Alembic commands ###
